# Generated by Django 4.2.2 on 2023-06-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_financas', '0003_expensecategory_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='default',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenuecategory',
            name='default',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
