# Generated by Django 4.2.2 on 2023-06-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_financas', '0004_alter_expensecategory_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
