# Generated by Django 4.2.2 on 2023-06-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_financas', '0005_expensecategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_financas.wallet'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='wallet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_financas.wallet'),
        ),
    ]
