# Generated by Django 4.2.2 on 2023-06-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_financas', '0007_wallet_created_at_wallet_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='wallet',
            new_name='wallet_id',
        ),
    ]
